#!/usr/bin/env bash


command="$1"


function plan {
    local total="$1"
    echo "1..$total"
}


testnum=0

function test {
    declare mode="$1"
    declare name="$2"
    declare -a input=("${!3}")
    declare expected="$4"

    local actual=$( printf '%s\n' "${input[@]}" | "$command" $mode )

    testnum=$(($testnum + 1))

    if [[ $expected == $actual ]]
    then
        echo "ok $testnum - $name"
    else
        echo "not ok $testnum - $name"
        echo "#        got: $actual"
        echo "#   expected: $expected"
    fi
}





plan 8


input=(+1 +1 +1)
test sum "simple addition" input[@] 3

input=(+1 +1 -2)
test sum "one subtraction" input[@] 0

input=(-1 -2 -3)
test sum "all subtraction" input[@] -6


input=(+1 -2 +3 +1)
test repeat "one loop" input[@] 2

input=(+1 -1)
test repeat "no loops" input[@] 0

input=(+3 +3 +4 -2 -4)
test repeat "one loop" input[@] 10

input=(-6 +3 +8 +5 -6)
test repeat "two loops" input[@] 5

input=(+7 +7 -2 -7 -4)
test repeat "two loops" input[@] 14
