#!/usr/bin/env bash


command="$1"


function plan {
    local total="$1"
    echo "1..$total"
}


testnum=0

function test {
    declare mode="$1"
    declare name="$2"
    declare -a input=("${!3}")
    declare expected="$4"

    local actual=$( printf '%s\n' "${input[@]}" | "$command" $mode )

    testnum=$(($testnum + 1))

    if [[ $expected == $actual ]]
    then
        echo "ok $testnum - $name"
    else
        echo "not ok $testnum - $name"
        echo "#        got: $actual"
        echo "#   expected: $expected"
    fi
}





plan 1


input=(
    abcdef
    bababc
    abbcde
    abcccd
    aabcdd
    abcdee
    ababab
)
test part1 "part 1: provided example" input[@] 12


input=(
    abcde
    fghij
    klmno
    pqrst
    fguij
    axcye
    wvxyz
)
test part2 "part 2: provided example" input[@] "fgij"
